name: neyvan-test3
version: 0.20.2
summary: Free, open source planetarium software
description: |
  Stellarium renders 3D photo-realistic skies in real-time. With Stellarium, you
  really see what you can see with your eyes, binoculars or a small telescope.
confinement: strict
grade: stable
base: core18

architectures:
   - build-on: amd64
   - build-on: i386
   - build-on: arm64

apps:
  neyvan-test3:
    command: desktop-launch $SNAP/bin/neyvan-test3
    plugs: [desktop, wayland, x11, unity7, opengl, network, network-bind, network-manager, home]

parts:
  neyvan-test3:
    plugin: cmake
    source: https://github.com/neyvan/neyvan-test3.git
    build-packages:
       - build-essential
       - qtbase5-dev

