name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
  pull_request:
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
jobs:
  Main:
    runs-on: ${{ matrix.os }}
    env:
      ECM_ROOT: 'C:\Program Files\ECM'
      CXXFLAGS: ${{ matrix.CXXFLAGS }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
        include:
          - os: ubuntu-18.04
            CXXFLAGS: '-Wall -Wextra -pedantic -Werror'
          - os: windows-latest
            extra-cmake-modules: '5.70.0'
            CXXFLAGS: '/W4 /WX'
    steps:
    - name: Enable Git symlinks
      if: runner.os == 'Windows'
      run: git config --global core.symlinks true

    - name: Clone repo
      uses: actions/checkout@v2.3.1
      with:
        submodules: true

    - name: Install dependent apt packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install extra-cmake-modules libqt5x11extras5-dev qttools5-dev qtmultimedia5-dev

    - name: Install Qt
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v2.7.2

    - name: Install Extra CMake Modules
      if: runner.os == 'Windows'
      run: |
        git clone --depth 1 --branch v${{ matrix.extra-cmake-modules }} https://github.com/KDE/extra-cmake-modules.git
        cmake -S extra-cmake-modules -B extra-cmake-modules/build
        cmake --build extra-cmake-modules/build --target install

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D PORTABLE_MODE=ON ..
        cmake --build . --parallel 2
